import type { IconType } from "react-icons";
import {
  FiAlertCircle,
  FiArrowLeft,
  FiArrowRight,
  FiChevronRight,
  FiBookOpen,
  FiBriefcase,
  FiCalendar,
  FiCast,
  FiCheck,
  FiCloud,
  FiCompass,
  FiDollarSign,
  FiFilm,
  FiFilter,
  FiGrid,
  FiHeadphones,
  FiHome,
  FiInfo,
  FiList,
  FiLock,
  FiMail,
  FiBell,
  FiMessageSquare,
  FiMusic,
  FiPenTool,
  FiPhone,
  FiPlay,
  FiPlus,
  FiSearch,
  FiShield,
  FiSmartphone,
  FiStar,
  FiTrash2,
  FiTrendingDown,
  FiTrendingUp,
  FiTv,
  FiUser,
  FiUsers,
  FiXCircle,
  FiFileText,
} from "react-icons/fi";
import {
  SiApplemusic,
  SiCanva,
  SiNetflix,
  SiSpotify,
} from "react-icons/si";
import { FcGoogle } from "react-icons/fc";

export const Icons = {
  home: FiHome,
  compass: FiCompass,
  list: FiList,
  user: FiUser,
  search: FiSearch,
  info: FiInfo,
  filter: FiFilter,
  calendar: FiCalendar,
  plus: FiPlus,
  users: FiUsers,
  shield: FiShield,
  trendingUp: FiTrendingUp,
  trendingDown: FiTrendingDown,
  dollarSign: FiDollarSign,
  alertCircle: FiAlertCircle,
  lock: FiLock,
  fileText: FiFileText,
  smartphone: FiSmartphone,
  star: FiStar,
  trash: FiTrash2,
  check: FiCheck,
  arrowLeft: FiArrowLeft,
  arrowRight: FiArrowRight,
  chevronRight: FiChevronRight,
  xCircle: FiXCircle,
  mail: FiMail,
  bell: FiBell,
  messageSquare: FiMessageSquare,
  phone: FiPhone,
  play: FiPlay,
  tv: FiTv,
  film: FiFilm,
  music: FiMusic,
  cloud: FiCloud,
  briefcase: FiBriefcase,
  penTool: FiPenTool,
  bookOpen: FiBookOpen,
  grid: FiGrid,
  headphones: FiHeadphones,
  cast: FiCast,
  siNetflix: SiNetflix,
  siSpotify: SiSpotify,
  siApplemusic: SiApplemusic,
  siCanva: SiCanva,
  google: FcGoogle,
} as const satisfies Record<string, IconType>;

export type IconName = keyof typeof Icons;
